name: Pruebas Automáticas (TDD)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Ejecutar Tests
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Versión recomendada para Next.js
          cache: "npm"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar linter
        run: npm run lint --if-present

      - name: Ejecutar pruebas (Jest/React Testing Library)
        run: npm test
